# Generated by Django 4.1.1 on 2022-09-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddf', '0003_post_image10_post_image11_post_image12_post_image13_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
                ('image3', models.ImageField(upload_to='images/')),
                ('image4', models.ImageField(upload_to='images/')),
                ('image5', models.ImageField(upload_to='images/')),
                ('image6', models.ImageField(upload_to='images/')),
                ('image7', models.ImageField(upload_to='images/')),
                ('image8', models.ImageField(upload_to='images/')),
                ('image9', models.ImageField(upload_to='images/')),
                ('image10', models.ImageField(upload_to='images/')),
                ('image11', models.ImageField(upload_to='images/')),
                ('image12', models.ImageField(upload_to='images/')),
                ('image13', models.ImageField(upload_to='images/')),
                ('image14', models.ImageField(upload_to='images/')),
                ('image15', models.ImageField(upload_to='images/')),
                ('image16', models.ImageField(upload_to='images/')),
                ('image17', models.ImageField(upload_to='images/')),
                ('image18', models.ImageField(upload_to='images/')),
                ('image19', models.ImageField(upload_to='images/')),
                ('image20', models.ImageField(upload_to='images/')),
                ('image21', models.ImageField(upload_to='images/')),
                ('image22', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='pot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
                ('image3', models.ImageField(upload_to='images/')),
                ('image4', models.ImageField(upload_to='images/')),
                ('image5', models.ImageField(upload_to='images/')),
                ('image6', models.ImageField(upload_to='images/')),
                ('image7', models.ImageField(upload_to='images/')),
                ('image8', models.ImageField(upload_to='images/')),
                ('image9', models.ImageField(upload_to='images/')),
                ('image10', models.ImageField(upload_to='images/')),
                ('image11', models.ImageField(upload_to='images/')),
                ('image12', models.ImageField(upload_to='images/')),
                ('image13', models.ImageField(upload_to='images/')),
                ('image14', models.ImageField(upload_to='images/')),
                ('image15', models.ImageField(upload_to='images/')),
                ('image16', models.ImageField(upload_to='images/')),
                ('image17', models.ImageField(upload_to='images/')),
                ('image18', models.ImageField(upload_to='images/')),
                ('image19', models.ImageField(upload_to='images/')),
                ('image20', models.ImageField(upload_to='images/')),
                ('image21', models.ImageField(upload_to='images/')),
                ('image22', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
