# Generated by Django 4.1.1 on 2022-09-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddf', '0004_pat_pot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pat',
            name='image13',
        ),
        migrations.RemoveField(
            model_name='pat',
            name='image14',
        ),
        migrations.RemoveField(
            model_name='pat',
            name='image15',
        ),
        migrations.RemoveField(
            model_name='pat',
            name='image16',
        ),
        migrations.RemoveField(
            model_name='pat',
            name='image17',
        ),
        migrations.RemoveField(
            model_name='pat',
            name='image18',
        ),
        migrations.RemoveField(
            model_name='pat',
            name='image19',
        ),
        migrations.RemoveField(
            model_name='pat',
            name='image20',
        ),
        migrations.RemoveField(
            model_name='pat',
            name='image21',
        ),
        migrations.RemoveField(
            model_name='pat',
            name='image22',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='image12',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='image13',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='image14',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='image15',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='image16',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='image17',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='image18',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='image19',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='image20',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='image21',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='image22',
        ),
    ]
