# Generated by Django 4.1.1 on 2022-09-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddf', '0005_remove_pat_image13_remove_pat_image14_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pat',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='pat',
            name='image11',
        ),
        migrations.RemoveField(
            model_name='pat',
            name='image12',
        ),
        migrations.RemoveField(
            model_name='pat',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='pat',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='pat',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='pat',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='pat',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='pat',
            name='image9',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='image11',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='image9',
        ),
    ]
